# Generated by Django 2.2 on 2019-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacionalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nomeDepartamento',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
