# Generated by Django 2.2 on 2019-08-15 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('rg', models.CharField(max_length=7, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('department', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Funcionario',
            },
        ),
        migrations.CreateModel(
            name='Apointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hr_entry', models.TimeField()),
                ('hr_exit', models.TimeField()),
                ('name_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ApointHourApp.Funcionario')),
            ],
            options={
                'db_table': 'Apointment',
            },
        ),
    ]
