# Generated by Django 2.2 on 2019-07-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=14)),
                ('Telefone', models.CharField(max_length=11)),
                ('Endereco', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'Cliente',
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Medicamento', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=30)),
                ('Peso_Volume', models.FloatField()),
            ],
            options={
                'db_table': 'Medicamento',
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome_Procedimento', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'Procedimento',
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('CPF', models.CharField(max_length=14)),
                ('CRMV', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Veterinario',
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
                ('Tipo', models.CharField(max_length=20)),
                ('Raca', models.CharField(max_length=20)),
                ('Idade', models.IntegerField()),
                ('Peso', models.FloatField()),
                ('Nome_Dono_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVet.Cliente')),
            ],
            options={
                'db_table': 'Paciente',
            },
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantidade', models.IntegerField()),
                ('Validade', models.DateField()),
                ('Medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVet.Medicamento')),
            ],
            options={
                'db_table': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='AcaoProcedimento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao_Procedimento', models.TextField(max_length=100)),
                ('OBS', models.TextField(max_length=100)),
                ('Paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVet.Paciente')),
                ('Procedimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVet.Procedimento')),
                ('Veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVet.Veterinario')),
            ],
            options={
                'db_table': 'Acao_Procedimento',
            },
        ),
    ]
