# Generated by Django 2.2 on 2019-08-12 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('dt_birthday', models.DateField()),
                ('cnh', models.CharField(max_length=12)),
                ('active', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'DeliveryMan',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_group', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_item', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('price', models.FloatField()),
                ('availability', models.BooleanField(default=1)),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AdmApp.Group')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
